name: clinic_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_flushbar: ^0.0.2
  font_awesome_flutter: ^10.2.1
  get_it: ^7.2.0
  http: ^0.13.5
  internet_connection_checker: ^0.0.1+4
  intl: ^0.17.0
  loader_overlay: ^2.0.7
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  device_preview: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"  
  min_sdk_android: 21  

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Bout
      fonts:
        - asset: assets/fonts/bout.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
